"""update test run table 270722

Revision ID: 037aac29dd4a
Revises: d7ace16d8881
Create Date: 2022-07-27 09:46:32.857308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '037aac29dd4a'
down_revision = 'd7ace16d8881'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('map_test_exec', sa.Column('started_date', sa.Integer(), nullable=True))
    op.add_column('map_test_exec', sa.Column('finished_date', sa.Integer(), nullable=True))
    op.add_column('test_repo', sa.Column('cloud_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_repo', 'cloud_id')
    op.drop_column('map_test_exec', 'finished_date')
    op.drop_column('map_test_exec', 'started_date')
    # ### end Alembic commands ###
