"""empty message

Revision ID: 0769e23df92f
Revises: 686aa37c43f9
Create Date: 2023-10-26 09:52:53.089666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0769e23df92f'
down_revision = '686aa37c43f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('tinh', sa.Text(collation='utf8mb4_unicode_ci'), nullable=True))
    op.add_column('orders', sa.Column('huyen', sa.Text(collation='utf8mb4_unicode_ci'), nullable=True))
    op.add_column('orders', sa.Column('xa', sa.Text(collation='utf8mb4_unicode_ci'), nullable=True))
    op.add_column('orders', sa.Column('loi_nhan', sa.Text(collation='utf8mb4_unicode_ci'), nullable=True))
    op.add_column('orders', sa.Column('ship_id', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('gia_ship', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('tong_thanh_toan', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'shipper', ['ship_id'], ['id'], onupdate='SET NULL', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'tong_thanh_toan')
    op.drop_column('orders', 'gia_ship')
    op.drop_column('orders', 'ship_id')
    op.drop_column('orders', 'loi_nhan')
    op.drop_column('orders', 'xa')
    op.drop_column('orders', 'huyen')
    op.drop_column('orders', 'tinh')
    # ### end Alembic commands ###
