"""empty message

Revision ID: 0bf51275a956
Revises: d5337d709172
Create Date: 2023-10-17 14:39:29.565147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bf51275a956'
down_revision = 'd5337d709172'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('old_price', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('giam_gia', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'giam_gia')
    op.drop_column('product', 'old_price')
    # ### end Alembic commands ###
