"""add test run custom field model

Revision ID: 0c83e07ec89b
Revises: 68893c507ca6
Create Date: 2023-01-13 17:07:32.549492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c83e07ec89b'
down_revision = '68893c507ca6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_run_fields',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('type_values', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=250), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('is_disabled', sa.Boolean(), nullable=True),
    sa.Column('is_native', sa.Boolean(), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('cloud_id', sa.String(length=50), nullable=True),
    sa.Column('project_key', sa.String(length=50), nullable=True),
    sa.Column('project_id', sa.String(length=50), nullable=True),
    sa.Column('site_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_type_test_run_fields',
    sa.Column('test_type_id', sa.String(length=50), nullable=False),
    sa.Column('test_run_field_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['test_run_field_id'], ['test_run_fields.id'], ),
    sa.ForeignKeyConstraint(['test_type_id'], ['test_type.id'], ),
    sa.PrimaryKeyConstraint('test_type_id', 'test_run_field_id')
    )
    op.add_column('test_type', sa.Column('cloud_id', sa.String(length=255), nullable=True))
    op.add_column('test_type', sa.Column('project_key', sa.String(length=50), nullable=True))
    op.add_column('test_type', sa.Column('project_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_type', 'project_id')
    op.drop_column('test_type', 'project_key')
    op.drop_column('test_type', 'cloud_id')
    op.drop_table('test_type_test_run_fields')
    op.drop_table('test_run_fields')
    # ### end Alembic commands ###
