"""empty message

Revision ID: 0fe2ab156b69
Revises: 53b47bcd8943
Create Date: 2023-06-29 20:12:56.053212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fe2ab156b69'
down_revision = '53b47bcd8943'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('comment', sa.Text(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_date', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('product', sa.Column('file_picture', sa.String(length=50), nullable=True))
    op.add_column('product', sa.Column('attached_file', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'attached_file')
    op.drop_column('product', 'file_picture')
    op.drop_table('reviews')
    # ### end Alembic commands ###
