"""empty message

Revision ID: 142360bdfd6a
Revises: f41ab4952958
Create Date: 2023-07-10 16:39:27.889143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '142360bdfd6a'
down_revision = 'f41ab4952958'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('comment', sa.Text(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_date', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('count_money_buy', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'count_money_buy')
    op.drop_table('reviews')
    # ### end Alembic commands ###
