"""empty message

Revision ID: 196369f39d64
Revises: 8484fe9a41b2
Create Date: 2023-04-27 20:46:35.956626

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '196369f39d64'
down_revision = '8484fe9a41b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('history_test', 'history_category',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_index(op.f('ix_history_test_history_category'), 'history_test', ['history_category'], unique=False)
    op.add_column('test_case', sa.Column('test_type_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_case', 'test_type_id')
    op.drop_index(op.f('ix_history_test_history_category'), table_name='history_test')
    op.alter_column('history_test', 'history_category',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
