"""add str date time

Revision ID: 198d0e91c47b
Revises: a5bd6715fa87
Create Date: 2022-07-15 14:49:38.177361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '198d0e91c47b'
down_revision = 'a5bd6715fa87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_timer', sa.Column('str_date_time', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_timer', 'str_date_time')
    # ### end Alembic commands ###
