"""update test enviroment model

Revision ID: 1cba06f38ac2
Revises: aa858592fb85
Create Date: 2023-02-01 10:37:46.080928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cba06f38ac2'
down_revision = 'aa858592fb85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_environments',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('cloud_id', sa.String(length=50), nullable=True),
    sa.Column('project_id', sa.String(length=50), nullable=True),
    sa.Column('created_date', sa.Integer(), nullable=True),
    sa.Column('modified_date', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_environments')
    # ### end Alembic commands ###
