"""init

Revision ID: 2546ac763036
Revises: 
Create Date: 2022-07-06 16:18:04.665983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2546ac763036'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('show', sa.Boolean(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('dynamic', sa.Boolean(), nullable=True),
    sa.Column('object', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_executions',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_sets',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_type',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('project_setting_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tests',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('cucumber', sa.String(length=255), nullable=True),
    sa.Column('generic', sa.String(length=255), nullable=True),
    sa.Column('issue_id', sa.String(length=255), nullable=False),
    sa.Column('test_type_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['test_type_id'], ['test_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('map_test_executions',
    sa.Column('test_id', sa.String(length=50), nullable=False),
    sa.Column('test_execution_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['test_execution_id'], ['test_executions.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('test_id', 'test_execution_id')
    )
    op.create_table('map_test_testsets',
    sa.Column('test_id', sa.String(length=50), nullable=False),
    sa.Column('testset_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
    sa.ForeignKeyConstraint(['testset_id'], ['test_sets.id'], ),
    sa.PrimaryKeyConstraint('test_id', 'testset_id')
    )
    op.create_table('test_steps',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('data', sa.String(length=255), nullable=True),
    sa.Column('result', sa.String(length=255), nullable=True),
    sa.Column('customFields', sa.Text(), nullable=True),
    sa.Column('attachments', sa.Text(), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=True),
    sa.Column('test_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_steps')
    op.drop_table('map_test_testsets')
    op.drop_table('map_test_executions')
    op.drop_table('tests')
    op.drop_table('users')
    op.drop_table('test_type')
    op.drop_table('test_sets')
    op.drop_table('test_executions')
    op.drop_table('message')
    # ### end Alembic commands ###
