"""add test step table.

Revision ID: 260af2624227
Revises: 8596c4acc114
Create Date: 2022-07-06 14:12:29.386780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '260af2624227'
down_revision = '8596c4acc114'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_steps',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('data', sa.String(length=255), nullable=True),
    sa.Column('result', sa.String(length=255), nullable=True),
    sa.Column('customFields', sa.Text(), nullable=True),
    sa.Column('attachments', sa.Text(), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=True),
    sa.Column('test_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_steps')
    # ### end Alembic commands ###
