"""empty message

Revision ID: 28657a23ce0f
Revises: 
Create Date: 2023-06-07 15:00:06.055315

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '28657a23ce0f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachment',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('attached_file', sa.Text(), nullable=True),
    sa.Column('file_name', sa.String(length=500), nullable=True),
    sa.Column('extension', sa.Text(), nullable=True),
    sa.Column('test_step_id', sa.Text(), nullable=True),
    sa.Column('created_date', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('modified_date', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('project_id', sa.String(length=50), nullable=True),
    sa.Column('cloud_id', sa.String(length=50), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('history_test',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('history_category', sa.Integer(), nullable=True),
    sa.Column('activities', sa.String(length=50), nullable=False),
    sa.Column('action_name', sa.String(length=50), nullable=False),
    sa.Column('detail_of_action', sa.JSON(), nullable=False),
    sa.Column('created_date', sa.Integer(), nullable=True),
    sa.Column('id_reference', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_history_test_created_date'), 'history_test', ['created_date'], unique=False)
    op.create_index(op.f('ix_history_test_history_category'), 'history_test', ['history_category'], unique=False)
    op.create_table('message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('show', sa.Boolean(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('dynamic', sa.Boolean(), nullable=True),
    sa.Column('object', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_table('project_setting',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Integer(), nullable=True),
    sa.Column('project_name', sa.String(length=255), nullable=True),
    sa.Column('project_id', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repository',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('folder_id', sa.String(length=50), nullable=True),
    sa.Column('parent_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('project_id', sa.String(length=50), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('cloud_id', sa.String(length=255), nullable=True),
    sa.Column('created_date', sa.Integer(), nullable=True),
    sa.Column('modified_date', sa.Integer(), nullable=True),
    sa.Column('type', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folder_id')
    )
    op.create_table('setting',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('miscellaneous', sa.Text(), nullable=True),
    sa.Column('test_type', sa.Text(), nullable=True),
    sa.Column('test_environment', sa.Text(), nullable=True),
    sa.Column('test_step_field', sa.Text(), nullable=True),
    sa.Column('test_run_custom_field', sa.Text(), nullable=True),
    sa.Column('test_test_executions_status', sa.Text(), nullable=True),
    sa.Column('reindex', sa.Text(), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.String(length=50), nullable=True),
    sa.Column('project_key', sa.String(length=50), nullable=True),
    sa.Column('cloud_id', sa.String(length=255), nullable=True),
    sa.Column('site_url', sa.String(length=255), nullable=True),
    sa.Column('created_date', sa.Integer(), nullable=True),
    sa.Column('modified_date', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_case',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('cloud_id', sa.String(length=50), nullable=True),
    sa.Column('project_id', sa.String(length=50), nullable=True),
    sa.Column('issue_id', sa.String(length=50), nullable=True),
    sa.Column('issue_key', sa.String(length=50), nullable=True),
    sa.Column('test_type_id', sa.String(length=50), nullable=True),
    sa.Column('created_date', sa.Integer(), nullable=True),
    sa.Column('modified_date', sa.Integer(), nullable=True),
    sa.Column('deleted_date', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_environment',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('parent_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=250, collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('url', sa.Text(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('cloud_id', sa.String(length=50), nullable=True),
    sa.Column('project_id', sa.String(length=50), nullable=True),
    sa.Column('created_date', sa.Integer(), nullable=True),
    sa.Column('modified_date', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_execution',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('cloud_id', sa.String(length=50), nullable=True),
    sa.Column('project_id', sa.String(length=50), nullable=True),
    sa.Column('issue_id', sa.String(length=50), nullable=True),
    sa.Column('issue_key', sa.String(length=50), nullable=True),
    sa.Column('created_date', sa.Integer(), nullable=True),
    sa.Column('modified_date', sa.Integer(), nullable=True),
    sa.Column('deleted_date', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_run_field',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('type_values', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=250), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('is_disabled', sa.Boolean(), nullable=True),
    sa.Column('is_native', sa.Boolean(), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('cloud_id', sa.String(length=50), nullable=True),
    sa.Column('project_key', sa.String(length=50), nullable=True),
    sa.Column('project_id', sa.String(length=50), nullable=True),
    sa.Column('site_url', sa.String(length=255), nullable=True),
    sa.Column('created_date', sa.Integer(), nullable=True),
    sa.Column('modified_date', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_set',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('cloud_id', sa.String(length=50), nullable=True),
    sa.Column('project_id', sa.String(length=50), nullable=True),
    sa.Column('issue_id', sa.String(length=50), nullable=True),
    sa.Column('issue_key', sa.String(length=50), nullable=True),
    sa.Column('created_date', sa.Integer(), nullable=True),
    sa.Column('modified_date', sa.Integer(), nullable=True),
    sa.Column('deleted_date', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_status',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('color', sa.String(length=255), nullable=True),
    sa.Column('is_show', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('cloud_id', sa.String(length=50), nullable=True),
    sa.Column('project_key', sa.String(length=50), nullable=True),
    sa.Column('project_id', sa.String(length=50), nullable=True),
    sa.Column('site_url', sa.String(length=255), nullable=True),
    sa.Column('created_date', sa.Integer(), nullable=True),
    sa.Column('modified_date', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_step_field',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('type_values', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=250), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('is_disabled', sa.Boolean(), nullable=True),
    sa.Column('is_native', sa.Boolean(), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('cloud_id', sa.String(length=50), nullable=True),
    sa.Column('project_key', sa.String(length=50), nullable=True),
    sa.Column('project_id', sa.String(length=50), nullable=True),
    sa.Column('site_url', sa.String(length=255), nullable=True),
    sa.Column('created_date', sa.Integer(), nullable=True),
    sa.Column('modified_date', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_setting',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('display_column', sa.Text(), nullable=True),
    sa.Column('created_date', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('modified_date', mysql.INTEGER(unsigned=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_setting_user_id'), 'user_setting', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_case_repositories',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('test_id', sa.String(length=50), nullable=True),
    sa.Column('repository_id', sa.String(length=50), nullable=True),
    sa.Column('create_date', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repository.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['test_case.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_case_repositories_create_date'), 'test_case_repositories', ['create_date'], unique=False)
    op.create_index(op.f('ix_test_case_repositories_repository_id'), 'test_case_repositories', ['repository_id'], unique=False)
    op.create_index(op.f('ix_test_case_repositories_test_id'), 'test_case_repositories', ['test_id'], unique=False)
    op.create_table('test_cases_test_executions',
    sa.Column('test_case_id', sa.String(length=50), nullable=False),
    sa.Column('test_execution_id', sa.String(length=50), nullable=False),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('is_archived', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_case.id'], ),
    sa.ForeignKeyConstraint(['test_execution_id'], ['test_execution.id'], ),
    sa.PrimaryKeyConstraint('test_case_id', 'test_execution_id')
    )
    op.create_table('test_cases_test_sets',
    sa.Column('test_case_id', sa.String(length=50), nullable=False),
    sa.Column('test_set_id', sa.String(length=50), nullable=False),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_case.id'], ),
    sa.ForeignKeyConstraint(['test_set_id'], ['test_set.id'], ),
    sa.PrimaryKeyConstraint('test_case_id', 'test_set_id')
    )
    op.create_table('test_executions_test_environments',
    sa.Column('test_execution_id', sa.String(length=50), nullable=False),
    sa.Column('test_environment_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['test_environment_id'], ['test_environment.id'], ),
    sa.ForeignKeyConstraint(['test_execution_id'], ['test_execution.id'], ),
    sa.PrimaryKeyConstraint('test_execution_id', 'test_environment_id')
    )
    op.create_table('test_field',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('key', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('project_setting_id', sa.String(length=50), nullable=True),
    sa.Column('created_date', sa.Integer(), nullable=True),
    sa.Column('modified_date', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_setting_id'], ['project_setting.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_run',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('cloud_id', sa.String(length=50), nullable=True),
    sa.Column('project_id', sa.String(length=50), nullable=True),
    sa.Column('issue_id', sa.String(length=50), nullable=True),
    sa.Column('issue_key', sa.String(length=50), nullable=True),
    sa.Column('test_case_id', sa.String(length=50), nullable=False),
    sa.Column('test_execution_id', sa.String(length=50), nullable=False),
    sa.Column('comment', sa.String(length=50), nullable=True),
    sa.Column('test_status_id', sa.String(length=50), nullable=True),
    sa.Column('assignee_account_id', sa.String(length=50), nullable=True),
    sa.Column('executed_account_id', sa.String(length=50), nullable=True),
    sa.Column('is_updated', sa.Boolean(), nullable=True),
    sa.Column('start_date', sa.Integer(), nullable=True),
    sa.Column('end_date', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.Integer(), nullable=True),
    sa.Column('modified_date', sa.Integer(), nullable=True),
    sa.Column('deleted_date', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_case.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_execution_id'], ['test_execution.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_status_id'], ['test_status.id'], onupdate='SET NULL', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', 'test_case_id', 'test_execution_id')
    )
    op.create_table('test_step',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('cloud_id', sa.String(length=255), nullable=True),
    sa.Column('project_key', sa.String(length=50), nullable=True),
    sa.Column('project_id', sa.String(length=50), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('custom_fields', sa.JSON(), nullable=True),
    sa.Column('attachments', sa.Text(), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('test_case_id', sa.String(length=50), nullable=False),
    sa.Column('test_case_id_reference', sa.String(length=50), nullable=True),
    sa.Column('created_date', sa.Integer(), nullable=True),
    sa.Column('modified_date', sa.Integer(), nullable=True),
    sa.Column('deleted_date', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_case.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_steps_config',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('key', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('project_setting_id', sa.String(length=50), nullable=True),
    sa.Column('created_date', sa.Integer(), nullable=True),
    sa.Column('modified_date', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_setting_id'], ['project_setting.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_type',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=255), nullable=True),
    sa.Column('order', sa.String(length=255), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('project_setting_id', sa.String(length=50), nullable=True),
    sa.Column('cloud_id', sa.String(length=255), nullable=True),
    sa.Column('project_key', sa.String(length=50), nullable=True),
    sa.Column('project_id', sa.String(length=50), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.Integer(), nullable=True),
    sa.Column('modified_date', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_setting_id'], ['project_setting.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_activity',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('test_run_id', sa.String(length=50), nullable=True),
    sa.Column('comment', sa.JSON(), nullable=True),
    sa.Column('status_change', sa.Text(), nullable=True),
    sa.Column('jira_user_id', sa.Text(), nullable=True),
    sa.Column('created_date', sa.Integer(), nullable=True),
    sa.Column('modified_date', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['test_run_id'], ['test_run.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_activity_created_date'), 'test_activity', ['created_date'], unique=False)
    op.create_table('test_cases_test_steps',
    sa.Column('test_case_id', sa.String(length=50), nullable=False),
    sa.Column('test_step_id', sa.String(length=50), nullable=False),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_case.id'], ),
    sa.ForeignKeyConstraint(['test_step_id'], ['test_step.id'], ),
    sa.PrimaryKeyConstraint('test_case_id', 'test_step_id')
    )
    op.create_table('test_step_detail',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('status_id', sa.String(length=50), nullable=True),
    sa.Column('test_step_id', sa.String(length=50), nullable=True),
    sa.Column('test_run_id', sa.String(length=50), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_date', sa.Integer(), nullable=True),
    sa.Column('modified_date', sa.Integer(), nullable=True),
    sa.Column('link', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['status_id'], ['test_status.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_run_id'], ['test_run.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_step_id'], ['test_step.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_step_detail_created_date'), 'test_step_detail', ['created_date'], unique=False)
    op.create_table('test_type_test_run_field',
    sa.Column('test_type_id', sa.String(length=50), nullable=False),
    sa.Column('test_run_field_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['test_run_field_id'], ['test_run_field.id'], ),
    sa.ForeignKeyConstraint(['test_type_id'], ['test_type.id'], ),
    sa.PrimaryKeyConstraint('test_type_id', 'test_run_field_id')
    )
    op.create_table('timer',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('test_run_id', sa.String(length=50), nullable=True),
    sa.Column('time_type', sa.Integer(), nullable=True),
    sa.Column('time_start', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('delta_time', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('created_date', sa.Integer(), nullable=True),
    sa.Column('modified_date', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['test_run_id'], ['test_run.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timer_created_date'), 'timer', ['created_date'], unique=False)
    op.create_table('defect',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('test_run_id', sa.String(length=50), nullable=True),
    sa.Column('test_step_detail_id', sa.String(length=50), nullable=True),
    sa.Column('test_issue_key', sa.Text(), nullable=True),
    sa.Column('test_issue_id', sa.Text(), nullable=True),
    sa.Column('created_date', sa.Integer(), nullable=True),
    sa.Column('modified_date', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['test_run_id'], ['test_run.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_step_detail_id'], ['test_step_detail.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_defect_created_date'), 'defect', ['created_date'], unique=False)
    op.create_table('test_evidence',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('test_run_id', sa.String(length=50), nullable=True),
    sa.Column('test_step_detail_id', sa.String(length=50), nullable=True),
    sa.Column('name_file', sa.String(length=250, collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('url_file', sa.Text(), nullable=True),
    sa.Column('created_date', sa.Integer(), nullable=True),
    sa.Column('modified_date', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['test_run_id'], ['test_run.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_step_detail_id'], ['test_step_detail.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_evidence_created_date'), 'test_evidence', ['created_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_evidence_created_date'), table_name='test_evidence')
    op.drop_table('test_evidence')
    op.drop_index(op.f('ix_defect_created_date'), table_name='defect')
    op.drop_table('defect')
    op.drop_index(op.f('ix_timer_created_date'), table_name='timer')
    op.drop_table('timer')
    op.drop_table('test_type_test_run_field')
    op.drop_index(op.f('ix_test_step_detail_created_date'), table_name='test_step_detail')
    op.drop_table('test_step_detail')
    op.drop_table('test_cases_test_steps')
    op.drop_index(op.f('ix_test_activity_created_date'), table_name='test_activity')
    op.drop_table('test_activity')
    op.drop_table('test_type')
    op.drop_table('test_steps_config')
    op.drop_table('test_step')
    op.drop_table('test_run')
    op.drop_table('test_field')
    op.drop_table('test_executions_test_environments')
    op.drop_table('test_cases_test_sets')
    op.drop_table('test_cases_test_executions')
    op.drop_index(op.f('ix_test_case_repositories_test_id'), table_name='test_case_repositories')
    op.drop_index(op.f('ix_test_case_repositories_repository_id'), table_name='test_case_repositories')
    op.drop_index(op.f('ix_test_case_repositories_create_date'), table_name='test_case_repositories')
    op.drop_table('test_case_repositories')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_setting_user_id'), table_name='user_setting')
    op.drop_table('user_setting')
    op.drop_table('test_step_field')
    op.drop_table('test_status')
    op.drop_table('test_set')
    op.drop_table('test_run_field')
    op.drop_table('test_execution')
    op.drop_table('test_environment')
    op.drop_table('test_case')
    op.drop_table('setting')
    op.drop_table('repository')
    op.drop_table('project_setting')
    op.drop_table('message')
    op.drop_index(op.f('ix_history_test_history_category'), table_name='history_test')
    op.drop_index(op.f('ix_history_test_created_date'), table_name='history_test')
    op.drop_table('history_test')
    op.drop_table('attachment')
    # ### end Alembic commands ###
