"""empty message

Revision ID: 30005b85993b
Revises: 4c095e14704d
Create Date: 2023-10-24 13:39:16.515809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30005b85993b'
down_revision = '4c095e14704d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dia_chi',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('tinh', sa.String(length=50, collation='utf8mb4_vietnamese_ci'), nullable=True),
    sa.Column('huyen', sa.String(length=50, collation='utf8mb4_vietnamese_ci'), nullable=True),
    sa.Column('xa', sa.String(length=50, collation='utf8mb4_vietnamese_ci'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dia_chi')
    # ### end Alembic commands ###
