"""empty message

Revision ID: 35fa3cab39f7
Revises: 64b7f94984e0
Create Date: 2023-04-21 15:21:32.880089

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '35fa3cab39f7'
down_revision = '64b7f94984e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history_test_set', 'subject')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history_test_set', sa.Column('subject', mysql.VARCHAR(length=50), nullable=False))
    # ### end Alembic commands ###
