"""add user_setting table

Revision ID: 3ff972d4a8b6
Revises: c27044c28ebf
Create Date: 2023-04-12 16:35:54.558211

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3ff972d4a8b6'
down_revision = 'c27044c28ebf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_setting',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('display_column', sa.Text(), nullable=True),
    sa.Column('created_date', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('modified_date', mysql.INTEGER(unsigned=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_setting_user_id'), 'user_setting', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_setting_user_id'), table_name='user_setting')
    op.drop_table('user_setting')
    # ### end Alembic commands ###
