"""add setting table

Revision ID: 40bcc5ea6cf3
Revises: 037aac29dd4a
Create Date: 2022-12-28 11:31:24.288807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40bcc5ea6cf3'
down_revision = '037aac29dd4a'
branch_labels = None
depends_on = None
from benedict import benedict


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setting',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('miscellaneous', sa.Text(), nullable=True),
    sa.Column('test_type', sa.Text(), nullable=True),
    sa.Column('test_environment', sa.Text(), nullable=True),
    sa.Column('test_step_field', sa.Text(), nullable=True),
    sa.Column('test_run_custom_field', sa.Text(), nullable=True),
    sa.Column('test_test_executions_status', sa.Text(), nullable=True),
    sa.Column('reindex', sa.Text(), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('setting')
    # ### end Alembic commands ###
