"""empty message

Revision ID: 422f2c4758de
Revises: 2ebabdfba7cc
Create Date: 2023-10-25 11:57:34.035814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '422f2c4758de'
down_revision = '2ebabdfba7cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tinh', sa.Text(collation='utf8mb4_unicode_ci'), nullable=True))
    op.add_column('user', sa.Column('huyen', sa.Text(collation='utf8mb4_unicode_ci'), nullable=True))
    op.add_column('user', sa.Column('xa', sa.Text(collation='utf8mb4_unicode_ci'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'xa')
    op.drop_column('user', 'huyen')
    op.drop_column('user', 'tinh')
    # ### end Alembic commands ###
