"""add test executions table.

Revision ID: 4bfa04ac5e22
Revises: 9d5d778014aa
Create Date: 2022-07-06 14:29:51.200744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bfa04ac5e22'
down_revision = '9d5d778014aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_executions',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('map_test_executions',
    sa.Column('test_id', sa.String(length=50), nullable=False),
    sa.Column('test_execution_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['test_execution_id'], ['test_executions.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('test_id', 'test_execution_id')
    )
    op.add_column('test_sets', sa.Column('name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_sets', 'name')
    op.drop_table('map_test_executions')
    op.drop_table('test_executions')
    # ### end Alembic commands ###
