"""update db

Revision ID: 4c3c8ed58ec6
Revises: e868a5f161ec
Create Date: 2023-02-06 17:17:11.287967

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4c3c8ed58ec6'
down_revision = 'e868a5f161ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_cases_test_sets',
    sa.Column('test_case_id', sa.String(length=50), nullable=False),
    sa.Column('test_set_id', sa.String(length=50), nullable=False),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_case.id'], ),
    sa.ForeignKeyConstraint(['test_set_id'], ['test_set.id'], ),
    sa.PrimaryKeyConstraint('test_case_id', 'test_set_id')
    )
    op.create_table('test_cases_test_steps',
    sa.Column('test_case_id', sa.String(length=50), nullable=False),
    sa.Column('test_step_id', sa.String(length=50), nullable=False),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_case.id'], ),
    sa.ForeignKeyConstraint(['test_step_id'], ['test_step.id'], ),
    sa.PrimaryKeyConstraint('test_case_id', 'test_step_id')
    )
    op.drop_table('tests_cases_test_sets')
    op.drop_table('tests_cases_test_steps')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tests_cases_test_steps',
    sa.Column('test_case_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('test_step_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('index', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_case.id'], name='tests_cases_test_steps_ibfk_1'),
    sa.ForeignKeyConstraint(['test_step_id'], ['test_step.id'], name='tests_cases_test_steps_ibfk_2'),
    sa.PrimaryKeyConstraint('test_case_id', 'test_step_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('tests_cases_test_sets',
    sa.Column('test_case_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('test_set_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('index', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_case.id'], name='tests_cases_test_sets_ibfk_1'),
    sa.ForeignKeyConstraint(['test_set_id'], ['test_set.id'], name='tests_cases_test_sets_ibfk_2'),
    sa.PrimaryKeyConstraint('test_case_id', 'test_set_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('test_cases_test_steps')
    op.drop_table('test_cases_test_sets')
    # ### end Alembic commands ###
