"""update model order item

Revision ID: 53b47bcd8943
Revises: 25923b3f45ba
Create Date: 2023-06-28 16:40:05.738411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53b47bcd8943'
down_revision = '25923b3f45ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'count')
    # ### end Alembic commands ###
