"""empty message

Revision ID: 588701c1e021
Revises: c58642325021
Create Date: 2023-05-26 14:25:55.177773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '588701c1e021'
down_revision = 'c58642325021'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_run', sa.Column('comment', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_run', 'comment')
    # ### end Alembic commands ###
