"""empty message

Revision ID: 64b7f94984e0
Revises: 1e6400ab0978
Create Date: 2023-04-21 09:52:57.272856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64b7f94984e0'
down_revision = '1e6400ab0978'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history_test_set',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('activities', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=50), nullable=False),
    sa.Column('action_name', sa.String(length=50), nullable=False),
    sa.Column('detail_of_action', sa.Text(), nullable=False),
    sa.Column('created_date', sa.Integer(), nullable=True),
    sa.Column('test_set_id', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_history_test_set_created_date'), 'history_test_set', ['created_date'], unique=False)
    op.create_index(op.f('ix_history_test_set_test_set_id'), 'history_test_set', ['test_set_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_history_test_set_test_set_id'), table_name='history_test_set')
    op.drop_index(op.f('ix_history_test_set_created_date'), table_name='history_test_set')
    op.drop_table('history_test_set')
    # ### end Alembic commands ###
