"""modify test step model

Revision ID: 675c4e522217
Revises: 0c83e07ec89b
Create Date: 2023-01-16 17:04:52.617701

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '675c4e522217'
down_revision = '0c83e07ec89b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_type', sa.Column('is_default', sa.Boolean(), nullable=True))
    op.drop_column('test_type', 'default')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_type', sa.Column('default', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('test_type', 'is_default')
    # ### end Alembic commands ###
