"""empty message

Revision ID: 686aa37c43f9
Revises: 422f2c4758de
Create Date: 2023-10-25 23:49:08.370973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '686aa37c43f9'
down_revision = '422f2c4758de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipper',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.Text(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('gia_ship', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipper')
    # ### end Alembic commands ###
