"""Change column name for test step field

Revision ID: 68893c507ca6
Revises: 7506fdb3f517
Create Date: 2023-01-10 14:01:11.661104

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '68893c507ca6'
down_revision = '7506fdb3f517'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_step_fields', sa.Column('is_required', sa.Boolean(), nullable=True))
    op.add_column('test_step_fields', sa.Column('is_disabled', sa.Boolean(), nullable=True))
    op.add_column('test_step_fields', sa.Column('is_native', sa.Boolean(), nullable=True))
    op.drop_column('test_step_fields', 'disabled')
    op.drop_column('test_step_fields', 'required')
    op.drop_column('test_step_fields', 'native')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_step_fields', sa.Column('native', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('test_step_fields', sa.Column('required', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('test_step_fields', sa.Column('disabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('test_step_fields', 'is_native')
    op.drop_column('test_step_fields', 'is_disabled')
    op.drop_column('test_step_fields', 'is_required')
    # ### end Alembic commands ###
