"""Update model for test step field

Revision ID: 7506fdb3f517
Revises: b33cb9c28b8e
Create Date: 2023-01-10 11:13:00.786818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7506fdb3f517'
down_revision = 'b33cb9c28b8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_step_fields',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('type_values', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=250), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('native', sa.Boolean(), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('cloud_id', sa.String(length=50), nullable=True),
    sa.Column('project_key', sa.String(length=50), nullable=True),
    sa.Column('project_id', sa.String(length=50), nullable=True),
    sa.Column('site_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('test_step_details', sa.Column('test_step_field_id', sa.String(length=50), nullable=True))
    op.add_column('test_step_details', sa.Column('data', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'test_step_details', 'test_step_fields', ['test_step_field_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('test_steps', sa.Column('project_key', sa.String(length=50), nullable=True))
    op.add_column('test_steps', sa.Column('project_id', sa.String(length=50), nullable=True))
    op.add_column('test_steps', sa.Column('issue_id', sa.String(length=255), nullable=False))
    op.add_column('test_steps', sa.Column('created_date', sa.Integer(), nullable=True))
    op.add_column('test_steps', sa.Column('modified_date', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_steps', 'modified_date')
    op.drop_column('test_steps', 'created_date')
    op.drop_column('test_steps', 'issue_id')
    op.drop_column('test_steps', 'project_id')
    op.drop_column('test_steps', 'project_key')
    op.drop_constraint(None, 'test_step_details', type_='foreignkey')
    op.drop_column('test_step_details', 'data')
    op.drop_column('test_step_details', 'test_step_field_id')
    op.drop_table('test_step_fields')
    # ### end Alembic commands ###
