"""empty message

Revision ID: 75bcd7a96187
Revises: 196369f39d64
Create Date: 2023-05-17 13:49:49.995392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75bcd7a96187'
down_revision = '196369f39d64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_step_detail', sa.Column('link', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_step_detail', 'link')
    # ### end Alembic commands ###
