"""empty message

Revision ID: 7b861c90fc7a
Revises: 5e32338946e0
Create Date: 2023-05-24 21:18:06.651909

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7b861c90fc7a'
down_revision = '5e32338946e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timer',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('test_run_id', sa.String(length=50), nullable=True),
    sa.Column('time_type', sa.Integer(), nullable=True),
    sa.Column('time_start', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('delta_time', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('created_date', sa.Integer(), nullable=True),
    sa.Column('modified_date', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['test_run_id'], ['test_run.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timer_created_date'), 'timer', ['created_date'], unique=False)
    op.drop_index('ix_test_timer_created_date', table_name='test_timer')
    op.drop_table('test_timer')
    # ### end Alembic commands ###