"""empty message

Revision ID: 8484fe9a41b2
Revises: 64b7f94984e0
Create Date: 2023-04-26 14:58:57.870079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8484fe9a41b2'
down_revision = '64b7f94984e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'test_run', 'test_execution', ['test_execution_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('test_step', sa.Column('test_case_id_reference', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_step', 'test_case_id_reference')
    op.drop_constraint(None, 'test_run', type_='foreignkey')
    # ### end Alembic commands ###
