"""update test status model

Revision ID: 84db18ee6ea9
Revises: 1cba06f38ac2
Create Date: 2023-02-01 10:59:28.838883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84db18ee6ea9'
down_revision = '1cba06f38ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_environments', sa.Column('url', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_environments', 'url')
    # ### end Alembic commands ###
