"""add test and test_type table.

Revision ID: 8596c4acc114
Revises: 05dfbfff9faf
Create Date: 2022-07-06 14:06:51.331601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8596c4acc114'
down_revision = '05dfbfff9faf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_type',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('project_setting_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tests',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('cucumber', sa.String(length=100), nullable=True),
    sa.Column('generic', sa.String(length=255), nullable=True),
    sa.Column('issue_id', sa.String(length=255), nullable=False),
    sa.Column('test_type_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['test_type_id'], ['test_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tests')
    op.drop_table('test_type')
    # ### end Alembic commands ###
