"""update db

Revision ID: 8ecae2dfbd10
Revises: 6e76b5de9770
Create Date: 2023-02-06 14:45:03.766384

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8ecae2dfbd10'
down_revision = '6e76b5de9770'
branch_labels = None
depends_on = None


def upgrade():
    op.drop_table('test_cases_test_sets')
    op.add_column('test_run', sa.Column('test_execution_id', sa.String(length=50), nullable=False))
    op.drop_constraint('test_run_ibfk_3', 'test_run', type_='foreignkey')
    op.create_foreign_key(None, 'test_run', 'test_execution', ['test_execution_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('test_run', 'test_test_execution_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_run', sa.Column('test_test_execution_id', mysql.VARCHAR(length=50), nullable=False))
    op.drop_constraint(None, 'test_run', type_='foreignkey')
    op.create_foreign_key('test_run_ibfk_3', 'test_run', 'test_execution', ['test_test_execution_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('test_run', 'test_execution_id')
    op.create_table('test_cases_test_sets',
    sa.Column('test_case_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('test_set_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('index', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_case.id'], name='test_cases_test_sets_ibfk_1'),
    sa.ForeignKeyConstraint(['test_set_id'], ['test_set.id'], name='test_cases_test_sets_ibfk_2'),
    sa.PrimaryKeyConstraint('test_case_id', 'test_set_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('tests_cases_test_sets')
    # ### end Alembic commands ###
