"""update cloud_id test execution

Revision ID: 95473c046ef9
Revises: caebf8234423
Create Date: 2022-07-21 10:24:31.002150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95473c046ef9'
down_revision = 'caebf8234423'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_executions', sa.Column('jira_id', sa.String(length=255), nullable=True))
    op.add_column('test_executions', sa.Column('cloud_id', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'test_executions', ['jira_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test_executions', type_='unique')
    op.drop_column('test_executions', 'cloud_id')
    op.drop_column('test_executions', 'jira_id')
    # ### end Alembic commands ###
