"""empty message

Revision ID: 97145008683d
Revises: 0769e23df92f
Create Date: 2023-10-27 21:25:56.543472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97145008683d'
down_revision = '0769e23df92f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('trang_thai', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'trang_thai')
    # ### end Alembic commands ###
