"""add index repo

Revision ID: 99a4db14f6b9
Revises: 4bbc67c13871
Create Date: 2022-07-12 17:44:20.565146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99a4db14f6b9'
down_revision = '4bbc67c13871'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_repo', sa.Column('index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_repo', 'index')
    # ### end Alembic commands ###
