"""update test keys

Revision ID: 9b734dca5745
Revises: f57c90d0ae24
Create Date: 2022-07-14 17:57:04.529434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b734dca5745'
down_revision = 'f57c90d0ae24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('key', sa.String(length=255), nullable=True))
    op.add_column('tests', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('tests', sa.Column('self', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'self')
    op.drop_column('tests', 'name')
    op.drop_column('tests', 'key')
    # ### end Alembic commands ###
