"""add test and test sets table.

Revision ID: 9d5d778014aa
Revises: 260af2624227
Create Date: 2022-07-06 14:24:37.068789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d5d778014aa'
down_revision = '260af2624227'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_sets',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('map_test_testsets',
    sa.Column('test_id', sa.String(length=50), nullable=False),
    sa.Column('testset_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
    sa.ForeignKeyConstraint(['testset_id'], ['test_sets.id'], ),
    sa.PrimaryKeyConstraint('test_id', 'testset_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('map_test_testsets')
    op.drop_table('test_sets')
    # ### end Alembic commands ###
