"""Add created_date and modified_date

Revision ID: a444660d2c22
Revises: 675c4e522217
Create Date: 2023-01-17 13:44:00.239968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a444660d2c22'
down_revision = '675c4e522217'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('setting', sa.Column('created_date', sa.Integer(), nullable=True))
    op.add_column('setting', sa.Column('modified_date', sa.Integer(), nullable=True))
    op.add_column('test_executions', sa.Column('created_date', sa.Integer(), nullable=True))
    op.add_column('test_executions', sa.Column('modified_date', sa.Integer(), nullable=True))
    op.add_column('test_field', sa.Column('created_date', sa.Integer(), nullable=True))
    op.add_column('test_field', sa.Column('modified_date', sa.Integer(), nullable=True))
    op.add_column('test_repo', sa.Column('created_date', sa.Integer(), nullable=True))
    op.add_column('test_repo', sa.Column('modified_date', sa.Integer(), nullable=True))
    op.add_column('test_run_fields', sa.Column('created_date', sa.Integer(), nullable=True))
    op.add_column('test_run_fields', sa.Column('modified_date', sa.Integer(), nullable=True))
    op.add_column('test_sets', sa.Column('created_date', sa.Integer(), nullable=True))
    op.add_column('test_sets', sa.Column('modified_date', sa.Integer(), nullable=True))
    op.add_column('test_step_fields', sa.Column('created_date', sa.Integer(), nullable=True))
    op.add_column('test_step_fields', sa.Column('modified_date', sa.Integer(), nullable=True))
    op.add_column('test_steps_config', sa.Column('created_date', sa.Integer(), nullable=True))
    op.add_column('test_steps_config', sa.Column('modified_date', sa.Integer(), nullable=True))
    op.add_column('test_type', sa.Column('created_date', sa.Integer(), nullable=True))
    op.add_column('test_type', sa.Column('modified_date', sa.Integer(), nullable=True))
    op.add_column('tests', sa.Column('created_date', sa.Integer(), nullable=True))
    op.add_column('tests', sa.Column('modified_date', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'modified_date')
    op.drop_column('tests', 'created_date')
    op.drop_column('test_type', 'modified_date')
    op.drop_column('test_type', 'created_date')
    op.drop_column('test_steps_config', 'modified_date')
    op.drop_column('test_steps_config', 'created_date')
    op.drop_column('test_step_fields', 'modified_date')
    op.drop_column('test_step_fields', 'created_date')
    op.drop_column('test_sets', 'modified_date')
    op.drop_column('test_sets', 'created_date')
    op.drop_column('test_run_fields', 'modified_date')
    op.drop_column('test_run_fields', 'created_date')
    op.drop_column('test_repo', 'modified_date')
    op.drop_column('test_repo', 'created_date')
    op.drop_column('test_field', 'modified_date')
    op.drop_column('test_field', 'created_date')
    op.drop_column('test_executions', 'modified_date')
    op.drop_column('test_executions', 'created_date')
    op.drop_column('setting', 'modified_date')
    op.drop_column('setting', 'created_date')
    # ### end Alembic commands ###
