"""update test status model

Revision ID: aa858592fb85
Revises: a444660d2c22
Create Date: 2023-01-31 10:51:45.238569

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aa858592fb85'
down_revision = 'a444660d2c22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_status', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('test_status', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('test_status', sa.Column('color', sa.String(length=255), nullable=True))
    op.add_column('test_status', sa.Column('is_show', sa.Boolean(), nullable=True))
    op.add_column('test_status', sa.Column('is_default', sa.Boolean(), nullable=True))
    op.add_column('test_status', sa.Column('cloud_id', sa.String(length=50), nullable=True))
    op.add_column('test_status', sa.Column('project_key', sa.String(length=50), nullable=True))
    op.add_column('test_status', sa.Column('project_id', sa.String(length=50), nullable=True))
    op.add_column('test_status', sa.Column('site_url', sa.String(length=255), nullable=True))
    op.add_column('test_status', sa.Column('created_date', sa.Integer(), nullable=True))
    op.add_column('test_status', sa.Column('modified_date', sa.Integer(), nullable=True))
    op.drop_column('test_status', 'value')
    op.drop_column('test_status', 'type')
    op.drop_column('test_status', 'project_setting_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_status', sa.Column('project_setting_id', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('test_status', sa.Column('type', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('test_status', sa.Column('value', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('test_status', 'modified_date')
    op.drop_column('test_status', 'created_date')
    op.drop_column('test_status', 'site_url')
    op.drop_column('test_status', 'project_id')
    op.drop_column('test_status', 'project_key')
    op.drop_column('test_status', 'cloud_id')
    op.drop_column('test_status', 'is_default')
    op.drop_column('test_status', 'is_show')
    op.drop_column('test_status', 'color')
    op.drop_column('test_status', 'description')
    op.drop_column('test_status', 'name')
    # ### end Alembic commands ###
