"""Update model setting

Revision ID: b33cb9c28b8e
Revises: 40bcc5ea6cf3
Create Date: 2022-12-28 13:27:14.087620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b33cb9c28b8e'
down_revision = '40bcc5ea6cf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('setting', sa.Column('project_id', sa.String(length=50), nullable=True))
    op.add_column('setting', sa.Column('project_key', sa.String(length=50), nullable=True))
    op.add_column('setting', sa.Column('cloud_id', sa.String(length=255), nullable=True))
    op.add_column('setting', sa.Column('site_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('setting', 'site_url')
    op.drop_column('setting', 'cloud_id')
    op.drop_column('setting', 'project_key')
    op.drop_column('setting', 'project_id')
    # ### end Alembic commands ###
