"""Init db 2

Revision ID: c27044c28ebf
Revises: e8d56ae1185f
Create Date: 2023-02-08 16:34:56.418329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c27044c28ebf'
down_revision = 'e8d56ae1185f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_executions_test_environments',
    sa.Column('test_execution_id', sa.String(length=50), nullable=False),
    sa.Column('test_environment_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['test_environment_id'], ['test_environment.id'], ),
    sa.ForeignKeyConstraint(['test_execution_id'], ['test_execution.id'], ),
    sa.PrimaryKeyConstraint('test_execution_id', 'test_environment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_executions_test_environments')
    # ### end Alembic commands ###
