"""add test timemer

Revision ID: c498498ce3bd
Revises: e15895a08fdd
Create Date: 2022-07-12 09:38:28.411362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c498498ce3bd'
down_revision = 'e15895a08fdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_timmer',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('map_test_exec_id', sa.String(length=50), nullable=True),
    sa.Column('time_type', sa.Integer(), nullable=True),
    sa.Column('date_time', sa.DATE(), nullable=True),
    sa.Column('created_date', sa.Integer(), nullable=True),
    sa.Column('modified_date', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['map_test_exec_id'], ['map_test_exec.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_timmer_created_date'), 'test_timmer', ['created_date'], unique=False)
    op.add_column('defects', sa.Column('created_date', sa.Integer(), nullable=True))
    op.add_column('defects', sa.Column('modified_date', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_defects_created_date'), 'defects', ['created_date'], unique=False)
    op.add_column('map_test_exec', sa.Column('created_date', sa.Integer(), nullable=True))
    op.add_column('map_test_exec', sa.Column('modified_date', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_map_test_exec_created_date'), 'map_test_exec', ['created_date'], unique=False)
    op.add_column('test_activity', sa.Column('created_date', sa.Integer(), nullable=True))
    op.add_column('test_activity', sa.Column('modified_date', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_test_activity_created_date'), 'test_activity', ['created_date'], unique=False)
    op.add_column('test_evidence', sa.Column('created_date', sa.Integer(), nullable=True))
    op.add_column('test_evidence', sa.Column('modified_date', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_test_evidence_created_date'), 'test_evidence', ['created_date'], unique=False)
    op.add_column('test_step_details', sa.Column('created_date', sa.Integer(), nullable=True))
    op.add_column('test_step_details', sa.Column('modified_date', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_test_step_details_created_date'), 'test_step_details', ['created_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_step_details_created_date'), table_name='test_step_details')
    op.drop_column('test_step_details', 'modified_date')
    op.drop_column('test_step_details', 'created_date')
    op.drop_index(op.f('ix_test_evidence_created_date'), table_name='test_evidence')
    op.drop_column('test_evidence', 'modified_date')
    op.drop_column('test_evidence', 'created_date')
    op.drop_index(op.f('ix_test_activity_created_date'), table_name='test_activity')
    op.drop_column('test_activity', 'modified_date')
    op.drop_column('test_activity', 'created_date')
    op.drop_index(op.f('ix_map_test_exec_created_date'), table_name='map_test_exec')
    op.drop_column('map_test_exec', 'modified_date')
    op.drop_column('map_test_exec', 'created_date')
    op.drop_index(op.f('ix_defects_created_date'), table_name='defects')
    op.drop_column('defects', 'modified_date')
    op.drop_column('defects', 'created_date')
    op.drop_index(op.f('ix_test_timmer_created_date'), table_name='test_timmer')
    op.drop_table('test_timmer')
    # ### end Alembic commands ###
