"""update model Repository

Revision ID: c9608ee4b9fd
Revises: 588701c1e021
Create Date: 2023-06-05 15:50:00.673986

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c9608ee4b9fd'
down_revision = '588701c1e021'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repository', sa.Column('type', sa.Boolean(), nullable=True))
    op.drop_index('ix_repository_create_date', table_name='repository')
    op.drop_column('repository', 'create_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repository', sa.Column('create_date', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True))
    op.create_index('ix_repository_create_date', 'repository', ['create_date'], unique=False)
    op.drop_column('repository', 'type')
    # ### end Alembic commands ###
