"""update model TestCasesTestExecutions for archived test case 

Revision ID: ca07ed186e26
Revises: c9608ee4b9fd
Create Date: 2023-06-07 11:19:37.398452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca07ed186e26'
down_revision = 'c9608ee4b9fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_cases_test_executions', sa.Column('is_archived', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_cases_test_executions', 'is_archived')
    # ### end Alembic commands ###
