"""update_key_test_repo

Revision ID: caebf8234423
Revises: 198d0e91c47b
Create Date: 2022-07-15 17:04:02.588317

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'caebf8234423'
down_revision = '198d0e91c47b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_repo', 'parent_id')
    op.add_column('test_repo', sa.Column('parent_id', sa.String(length=50), nullable=True))
    op.add_column('map_test_repo', sa.Column('index', sa.Integer(), nullable=True))
    op.add_column('test_repo', sa.Column('folder_id', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'test_repo', ['folder_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test_repo', type_='unique')
    op.alter_column('test_repo', 'parent_id',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.drop_column('test_repo', 'folder_id')
    op.drop_column('map_test_repo', 'index')
    # ### end Alembic commands ###
