"""add cloud id

Revision ID: d7ace16d8881
Revises: 95473c046ef9
Create Date: 2022-07-23 11:38:57.033896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7ace16d8881'
down_revision = '95473c046ef9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_sets', sa.Column('cloud_id', sa.String(length=255), nullable=True))
    op.add_column('test_steps', sa.Column('cloud_id', sa.String(length=255), nullable=True))
    op.add_column('tests', sa.Column('cloud_id', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'cloud_id')
    op.drop_column('test_steps', 'cloud_id')
    op.drop_column('test_sets', 'cloud_id')
    # ### end Alembic commands ###
