"""update test set key

Revision ID: e27af153c9a1
Revises: ec7d554e667c
Create Date: 2022-07-14 09:02:28.845492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e27af153c9a1'
down_revision = 'ec7d554e667c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_sets', sa.Column('key', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_sets', 'key')
    # ### end Alembic commands ###
