"""Init db 2

Revision ID: e868a5f161ec
Revises: 8ecae2dfbd10
Create Date: 2023-02-06 17:15:55.843439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e868a5f161ec'
down_revision = '8ecae2dfbd10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tests_cases_test_steps',
    sa.Column('test_case_id', sa.String(length=50), nullable=False),
    sa.Column('test_step_id', sa.String(length=50), nullable=False),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_case.id'], ),
    sa.ForeignKeyConstraint(['test_step_id'], ['test_step.id'], ),
    sa.PrimaryKeyConstraint('test_case_id', 'test_step_id')
    )
    op.add_column('test_run', sa.Column('is_updated', sa.Boolean(), nullable=True))
    op.drop_index('test_test_execution_id', table_name='test_run')
    op.create_foreign_key(None, 'test_run', 'test_execution', ['test_execution_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test_run', type_='foreignkey')
    op.create_index('test_test_execution_id', 'test_run', ['test_execution_id'], unique=False)
    op.drop_column('test_run', 'is_updated')
    op.drop_table('tests_cases_test_steps')
    # ### end Alembic commands ###
