"""update db

Revision ID: e8d56ae1185f
Revises: 66a04f1201bc
Create Date: 2023-02-08 15:03:11.029105

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e8d56ae1185f'
down_revision = '66a04f1201bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_run', sa.Column('executed_account_id', sa.String(length=50), nullable=True))
    op.add_column('test_run', sa.Column('start_date', sa.Integer(), nullable=True))
    op.add_column('test_run', sa.Column('end_date', sa.Integer(), nullable=True))
    op.drop_column('test_run', 'executed__account_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_run', sa.Column('executed__account_id', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('test_run', 'end_date')
    op.drop_column('test_run', 'start_date')
    op.drop_column('test_run', 'executed_account_id')
    # ### end Alembic commands ###
