"""add parent_id in TestEnvironment  model

Revision ID: e8dedc9797de
Revises: 84db18ee6ea9
Create Date: 2023-02-01 14:22:38.982253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8dedc9797de'
down_revision = '84db18ee6ea9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_environments', sa.Column('parent_id', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_environments', 'parent_id')
    # ### end Alembic commands ###
