"""update_key_test_execution

Revision ID: ec7d554e667c
Revises: 99a4db14f6b9
Create Date: 2022-07-13 15:08:41.912494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec7d554e667c'
down_revision = '99a4db14f6b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_executions', sa.Column('key', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_executions', 'key')
    # ### end Alembic commands ###
