"""empty message

Revision ID: edfff9d96eea
Revises: 142360bdfd6a
Create Date: 2023-07-10 17:06:51.380722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edfff9d96eea'
down_revision = '142360bdfd6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('revenue', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('count_sold', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'count_sold')
    op.drop_column('product', 'revenue')
    # ### end Alembic commands ###
