"""update message table

Revision ID: fe29cf75d5ab
Revises: 2546ac763036
Create Date: 2022-07-06 16:22:21.620356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe29cf75d5ab'
down_revision = '2546ac763036'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('message_id', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'message', ['message_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='unique')
    op.drop_column('message', 'message_id')
    # ### end Alembic commands ###
