"""add model run execution

Revision ID: ff927e5d4b72
Revises: fe29cf75d5ab
Create Date: 2022-07-12 10:35:31.713534

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ff927e5d4b72'
down_revision = 'fe29cf75d5ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_status',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('project_setting_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('map_test_exec',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('test_id', sa.String(length=50), nullable=True),
    sa.Column('exec_id', sa.String(length=50), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.String(length=50), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_date', sa.Integer(), nullable=True),
    sa.Column('modified_date', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exec_id'], ['test_executions.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['test_status.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_map_test_exec_created_date'), 'map_test_exec', ['created_date'], unique=False)
    op.create_table('test_activity',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('map_test_exec_id', sa.String(length=50), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('status_change', sa.Text(), nullable=True),
    sa.Column('jira_user_id', sa.Text(), nullable=True),
    sa.Column('created_date', sa.Integer(), nullable=True),
    sa.Column('modified_date', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['map_test_exec_id'], ['map_test_exec.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_activity_created_date'), 'test_activity', ['created_date'], unique=False)
    op.create_table('test_step_details',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('status_id', sa.String(length=50), nullable=True),
    sa.Column('test_step_id', sa.String(length=50), nullable=True),
    sa.Column('map_test_exec_id', sa.String(length=50), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_date', sa.Integer(), nullable=True),
    sa.Column('modified_date', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['map_test_exec_id'], ['map_test_exec.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['status_id'], ['test_status.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_step_id'], ['test_steps.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_step_details_created_date'), 'test_step_details', ['created_date'], unique=False)
    op.create_table('test_timer',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('map_test_exec_id', sa.String(length=50), nullable=True),
    sa.Column('time_type', sa.Integer(), nullable=True),
    sa.Column('date_time', sa.DATE(), nullable=True),
    sa.Column('created_date', sa.Integer(), nullable=True),
    sa.Column('modified_date', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['map_test_exec_id'], ['map_test_exec.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_timer_created_date'), 'test_timer', ['created_date'], unique=False)
    op.create_table('defects',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('map_test_exec_id', sa.String(length=50), nullable=True),
    sa.Column('test_step_detail_id', sa.String(length=50), nullable=True),
    sa.Column('test_issue_key', sa.Text(), nullable=True),
    sa.Column('test_issue_id', sa.Text(), nullable=True),
    sa.Column('created_date', sa.Integer(), nullable=True),
    sa.Column('modified_date', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['map_test_exec_id'], ['map_test_exec.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_step_detail_id'], ['test_step_details.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_defects_created_date'), 'defects', ['created_date'], unique=False)
    op.create_table('test_evidence',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('map_test_exec_id', sa.String(length=50), nullable=True),
    sa.Column('test_step_detail_id', sa.String(length=50), nullable=True),
    sa.Column('name_file', sa.Text(), nullable=True),
    sa.Column('url_file', sa.Text(), nullable=True),
    sa.Column('created_date', sa.Integer(), nullable=True),
    sa.Column('modified_date', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['map_test_exec_id'], ['map_test_exec.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_step_detail_id'], ['test_step_details.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_evidence_created_date'), 'test_evidence', ['created_date'], unique=False)
    op.drop_constraint('test_steps_ibfk_1', 'test_steps', type_='foreignkey')
    op.create_foreign_key(None, 'test_steps', 'tests', ['test_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('test_type', sa.Column('index', sa.Integer(), autoincrement=True, nullable=True))
    op.add_column('test_type', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('test_type', sa.Column('kind', sa.String(length=255), nullable=True))
    op.add_column('test_type', sa.Column('order', sa.String(length=255), nullable=True))
    op.add_column('test_type', sa.Column('default', sa.String(length=255), nullable=True))
    op.drop_column('test_type', 'value')
    op.drop_column('test_type', 'type')
    op.add_column('tests', sa.Column('issue_jira_id', sa.String(length=255), nullable=True))
    op.add_column('tests', sa.Column('test_repo', sa.String(length=255), nullable=True))
    op.add_column('tests', sa.Column('project_id', sa.String(length=50), nullable=False))
    op.alter_column('tests', 'test_type_id',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tests', 'test_type_id',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.drop_column('tests', 'project_id')
    op.drop_column('tests', 'test_repo')
    op.drop_column('tests', 'issue_jira_id')
    op.add_column('test_type', sa.Column('type', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('test_type', sa.Column('value', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('test_type', 'default')
    op.drop_column('test_type', 'order')
    op.drop_column('test_type', 'kind')
    op.drop_column('test_type', 'name')
    op.drop_column('test_type', 'index')
    op.drop_constraint(None, 'test_steps', type_='foreignkey')
    op.create_foreign_key('test_steps_ibfk_1', 'test_steps', 'tests', ['test_id'], ['id'])
    op.drop_index(op.f('ix_test_evidence_created_date'), table_name='test_evidence')
    op.drop_table('test_evidence')
    op.drop_index(op.f('ix_defects_created_date'), table_name='defects')
    op.drop_table('defects')
    op.drop_index(op.f('ix_test_timer_created_date'), table_name='test_timer')
    op.drop_table('test_timer')
    op.drop_index(op.f('ix_test_step_details_created_date'), table_name='test_step_details')
    op.drop_table('test_step_details')
    op.drop_index(op.f('ix_test_activity_created_date'), table_name='test_activity')
    op.drop_table('test_activity')
    op.drop_index(op.f('ix_map_test_exec_created_date'), table_name='map_test_exec')
    op.drop_table('map_test_exec')
    op.drop_table('test_status')
    # ### end Alembic commands ###
